Create a 1-D array of 10 evenly spaced values between 0 and 1, and then reshape the array to a 2-D array of shape (5, 2).

In [12]:
import numpy as np
array1 = np.linspace(0, 1, 10)
array1 = array1.reshape(5, 2)
print(array1)

[[0.         0.11111111]
 [0.22222222 0.33333333]
 [0.44444444 0.55555556]
 [0.66666667 0.77777778]
 [0.88888889 1.        ]]


Create a 2-D array of shape (3, 4) with random values and then extract the second and third rows.

In [13]:
import numpy as np
array1 = np.random.randint(1,100,12).reshape(3,4)
print(array1[1:3])

[[92 70 98 94]
 [62 32  4  6]]


Create a 2-D array of shape (4, 4) with random values and then extract the second and third columns.

In [14]:
import numpy as np
array1 = np.random.randint(1,100,16).reshape(4,4)
print(print(array1[:,1:3]))

[[87 99]
 [33 96]
 [28 95]
 [ 5 94]]
None


Create a 2-D array of shape (5, 5) with random values and then extract the diagonal of the array.

In [15]:
import numpy as np
array1 = np.random.randint(1,100,25).reshape(5,5)
print(np.diag(array1))

[86 19 29 63 65]


Create a 2-D array of shape (3, 3) with random values and then calculate the determinant of the array using numpy.

In [16]:
import numpy as np
array1 = np.random.randint(1,100,9).reshape(3,3)
print(np.linalg.det(array1))


-120941.99999999996


Create a 2-D array of shape (2, 3) with random values and then perform matrix multiplication of the array with its transpose.

In [17]:
import numpy as np
array1 = np.random.randint(1,100,6).reshape(2,3)
print(np.dot(array1, np.transpose(array1)))

[[16664 11398]
 [11398 15638]]


Create a 1-D array of shape (10) with random values and then find the index of the maximum value using numpy.

In [23]:
import numpy as np
array1 = np.random.randint(1,100,10)
print(np.argmax(array1))


0


Create a 2-D array of shape (4, 4) with random values and then sort the array along the first axis.


In [19]:
import numpy as np
array1 = np.random.randint(1,100,16).reshape(4,4)
print(np.sort(array1, axis=0))

[[63 23 47 34]
 [72 37 53 69]
 [72 77 65 91]
 [99 89 69 97]]


Create a 2-D array of shape (4, 4) with random values and then calculate the mean, median and standard deviation of the array along the second axis.


In [25]:
import numpy as np
array1 = np.random.randint(1,100,16).reshape(4,4)
print(array1)
print(np.mean(array1, axis=1))
print(np.median(array1, axis=1))
print(np.std(array1, axis=1))


[[63 55 74 89]
 [ 5 50 49 97]
 [94 21 52 23]
 [12 21 91 80]]
[70.25 50.25 47.5  51.  ]
[68.5 49.5 37.5 50.5]
[12.75490102 32.53747839 29.51694429 34.86402157]


Create a 1-D array of shape (10) with random values and then save the array to a binary file, load the array from the binary file and then compare it with the original array to check if they are equal.

In [27]:
import numpy as np
array1 = np.random.randint(1,100,10)
np.save("array.npy",array1)
array2 = np.load("array.npy")
print(array1 == array2)


[ True  True  True  True  True  True  True  True  True  True]
